# Generated by Django 4.1.5 on 2023-01-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.CharField(default='*', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='*', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.CharField(default='*', max_length=12),
            preserve_default=False,
        ),
    ]
